### ISSUE TITLE
Error when upload specific picture

### ISSUE THREAD

**Issue by Erimelowo** [JaredSchreiber/supremereality#2]
Hey, I get this error:

> **413 Request Entity Too Large**
nginx/1.14.0 (Ubuntu)

when uploading a specific picture (that is 2.9 MB and a .png). The error doesn't happen with bigger pictures (that take like 13 MB) and I tried uploading it multiple times on different topics. The picture is a screenshot taken with a mac.

Here's the error: https://imgur.com/BWq2prT
And here's the picture: https://we.tl/t-uVN6817yNc (will be deleted in 7 days)

I could still upload the picture if I wanted by exporting with Gimp or whatever, but you should probably fix this if you're able to. 
The error does mention Ubuntu (which, I guess, is what you're using), so it may work on different Linux distributions or something, you know that better than me.
Have a good day.

**Comment by 8b2eef7c901269e8e9a6ec532d57b6b1** [comment]
Hey louka,
this problem is covered in the readme under '[common problems](https://github.com/8b2eef7c901269e8e9a6ec532d57b6b1/supremereality#common-problems)' . Essentially it happens because the file upload limit on the reverse proxy (nginx) is lower than the total size of whatever you're trying to post. On SR i believe the limit is just 2 megabytes as it is a demo app. On installation of the software you can change the upload limit in core.clj, and also you have to change the settings in nginx or whatever you're using to front the app. It can be set to any arbitrary limit.

On supreme reality, I'm probably going to keep the limit as just being 2 MB but it is configurable in any installation.

**Comment by Erimelowo** [comment]
Oh, you're right, I thought I sent something with a bigger size than 2.9 MB in the past, but it was actually a jpg that was very compressed... I just took something with the same resolution (both were wallpapers btw) and checked the size so I thought it was around 13 MB, so it's my fault.
Thanks for answering.
Have a good day.
